### ISSUE TITLE
Add MarketData GC messages

### ISSUE THREAD

**Issue by srabouin** [seishun/node-tf2#2]
Hello,

Would it be possible to add the MarketData messages to the tf2 module? It seems like this would be the most efficient way to gather market prices. 

# The messages

https://github.com/SteamRE/SteamKit/blob/master/Resources/Protobufs/tf/base_gcmessages.proto#L479
```
message CMsgGCClientMarketDataRequest {
	optional uint32 user_currency = 1;
}

message CMsgGCClientMarketDataEntry {
	optional uint32 item_def_index = 1;
	optional uint32 item_quality = 2;
	optional uint32 item_sell_listings = 3;
	optional uint32 price_in_local_currency = 4;
}

message CMsgGCClientMarketData {
	repeated .CMsgGCClientMarketDataEntry entries = 1;
}
```
# The IDs
https://github.com/SteamRE/SteamKit/blob/master/Resources/Protobufs/tf/econ_gcmessages.proto#L73
```
k_EMsgGCClientRequestMarketData = 1080;
k_EMsgGCClientRequestMarketDataResponse = 1081;
```
# Other info
I got this working but my code is ugly, I figured I would share the information I gathered as it may be useful to others.

Currency 2001 is USD. CMsgGCClientMarketDataRequest returns CMsgGCClientMarketData with data filled like this:
```
{ itemDefIndex: 58,
  itemQuality: 3,
  itemSellListings: 2675,
  priceInLocalCurrency: 8 },
{ itemDefIndex: 58,
  itemQuality: 11,
  itemSellListings: 594,
  priceInLocalCurrency: 14 },
{ itemDefIndex: 58,
  itemQuality: 14,
  itemSellListings: 3,
  priceInLocalCurrency: 1667 }
```

It kind of is useless in a way because items with killstreak are not identified, nor are australium weapons so you can get multiple instances of the same defindex/quality combo.

**Comment by seishun** [comment]
I no longer maintain this project.
