### ISSUE TITLE
Error when crafting items

### ISSUE THREAD

**Issue by Ax6** [seishun/node-tf2#5]
I have updated to the new node-steam (v0.6.8) using Node.js v0.12
When crafting items I'm now getting the following error:

    buffer.writeUInt64LE(items[i], 4 + i * 8);
               ^
    TypeError: undefined is not a function

Is there any reason behind this? I've seen some buffer related changes in the latest commits, I might have to require some different module, maybe?

**Comment by LuaTenshi** [comment]
Getting the same error with a different NodeJS addon. Are writeUInt64LE and friends, no longer supported?

**Comment by andrewda** [comment]
Same thing here. Anyone find a fix?

**Comment by LuaTenshi** [comment]
Yeah, what happened is that node-steam no longer uses https://www.npmjs.com/package/ref it now uses https://www.npmjs.com/package/bytebuffer

You can look here... https://github.com/scholtzm/node-steam-groups/issues/2 to see how you would resolve the problem. It does however involve some coding.

**Comment by scholtzm** [comment]
You will most likely want to use [DoctorMcKay/node-tf2](https://github.com/DoctorMcKay/node-tf2) which is up-to-date and offers a lot more.

**Comment by andrewda** [comment]
Works great, scholtzm. Thank you!

**Comment by seishun** [comment]
I no longer maintain this project.
